# Generated by Django 4.2 on 2023-04-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.CharField(default='main', max_length=255),
        ),
    ]
